stages:
- stage: CI
  condition: not(or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), startsWith(variables['Build.SourceBranchName'], 'release-')))
  jobs:
  - job:
    pool:
      vmImage: $(imageName)
    strategy:
      matrix:
        mac:
          imageName: 'macOS-10.14'
          python.version: '3.7'
          SDKROOT: '/Applications/Xcode_10.3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk'
          TILEDB_SERIALIZATION: ON
        windows:
          imageName: 'windows-latest'
          python.version: '3.7'
          TILEDB_SERIALIZATION: ON
        linux_py3:
          imageName: 'ubuntu-latest'
          python.version: '3.6'
          TILEDB_SERIALIZATION: ON
      maxParallel: 4

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    # Print python and pip version information for debugging.
    # Azure pipelines windows images have been unstable or out of sync, causing
    # build failures in the pip step below when the 'bash' task uses the wrong
    # python or has issue that causes un-corrected cygwin-style paths to be
    # passed to pip.
    - bash: |
        echo "==== Python information ===="
        which python
        which pip
        python --version
        echo "============================"
      displayName: 'Print python version in bash task'

    - script: |
        printenv
      displayName: 'Print env'

    - script: |
        python -m pip install --upgrade -r misc/requirements_ci.txt
      displayName: 'Install dependencies'

    - script: |
        # vcvarsall is necessary so that numpy uses the correct compiler
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        python setup.py build_ext --inplace
        python setup.py install
      displayName: 'Build TileDB and TileDB-Py extension (Windows)'
      condition: eq(variables['Agent.OS'], 'Windows_NT')

    - bash: |
        set -xeo pipefail
        python setup.py build_ext --inplace --werror
        python setup.py install
      displayName: 'Build TileDB and TileDB-Py extension (POSIX)'
      condition: ne(variables['Agent.OS'], 'Windows_NT')

    - bash: |
        set -xeo pipefail

        pytest -vv

        # Test wheel build, install, and run
        python setup.py bdist_wheel
        #whl_file=`pwd`/dist/`ls dist/*.whl`
        mkdir /tmp/wheel_test
        cp dist/*.whl /tmp/wheel_test
        pushd /tmp/wheel_test
        ls
        pip install *.whl
        python -c "import tiledb ; tiledb.libtiledb.version()"
      displayName: 'Run tests'

    - bash: |
        set -xeo pipefail
        # Display log files if the build failed
        echo "Dumping log files for failed build"
        echo "----------------------------------"
        for f in $(find $BUILD_REPOSITORY_LOCALPATH/build -name *.log);
          do echo "------"
             echo $f
             echo "======"
             cat $f
          done;
      condition: failed() # only run this job if the build step failed
      displayName: "Print log files (failed build only)"
