stages:
  - stage: Release
    variables:
      ? ${{ if startsWith(variables['Build.SourceBranchName'], 'azure-wheel-test-') }}
      : TILEDBPY_VERSION: dev
        LIBTILEDB_VERSION: dev
        LIBTILEDB_SHA: dev
      ${{ else }}:
        TILEDBPY_VERSION: 0.28.0
        # NOTE: *must* update both LIBTILEDB_VERSION and LIBTILEDB_SHA
        LIBTILEDB_VERSION: "2.22.0"
        # NOTE: *must* update both LIBTILEDB_VERSION and LIBTILEDB_SHA
        LIBTILEDB_SHA: 52e981ee9ce92eaceaf13a79a5a95820eca0673b
      LIBTILEDB_REPO: https://github.com/TileDB-Inc/TileDB
      TILEDB_SRC: "$(Build.Repository.Localpath)/tiledb_src"
      TILEDB_BUILD: "$(Build.Repository.Localpath)/tiledb_build"
      TILEDB_GCS: ON # set here, override for macOS-arm64
      # UPDATE TILEDB_INSTALL:
      # - IN macOS sections below too!
      # - IN azure-libtiledb-darwin.yml 'path' input, if applicable
      TILEDB_INSTALL: "$(Pipeline.Workspace)/.libtiledb_dist/$(LIBTILEDB_SHA)"
    condition: or(startsWith(variables['Build.SourceBranch'], 'refs/tags'), startsWith(variables['Build.SourceBranchName'], 'release-'), startsWith(variables['Build.SourceBranchName'], 'azure-wheel-test-'))

    jobs:
      - job: build1_libtiledb
        timeoutInMinutes: 120
        strategy:
          matrix:
            macOS_libtiledb:
              imageName: "macOS-12"
              CMAKE_OSX_ARCHITECTURES: "x86_64"
              MACOSX_DEPLOYMENT_TARGET: 11
              TILEDB_INSTALL: "$(Pipeline.Workspace)/.libtiledb_dist/$(LIBTILEDB_SHA)-macos-x86_64"
            macOS_libtiledb_arm64:
              imageName: "macOS-12"
              CMAKE_OSX_ARCHITECTURES: "arm64"
              MACOSX_DEPLOYMENT_TARGET: 11
              BUILD_MAGIC_MACOS_UNIVERSAL: "ON"
              TILEDB_INSTALL: "$(Pipeline.Workspace)/.libtiledb_dist/$(LIBTILEDB_SHA)-macos-arm64"
            windows_libtiledb:
              imageName: "windows-latest"
              CMAKE_OSX_ARCHITECTURES: ""
        pool:
          vmImage: $(imageName)

        steps:
          - task: UsePythonVersion@0
          - template: azure-libtiledb-darwin.yml

      - job: build1_libtiledb_on_linux
        timeoutInMinutes: 120
        pool:
          vmImage: "ubuntu-latest"
        container: ghcr.io/ihnorton/tiledb-manylinux2014_x86_64:2023-04-02
        variables:
          CXXFLAGS: "-Wno-unused-parameter -lrt -DKJ_USE_EPOLL10 -D__BIONIC__=1"
          CFLAGS: "-Wno-unused-parameter -lrt -DKJ_USE_EPOLL=0 -D__BIONIC__=1"
          CMAKE_OSX_ARCHITECTURES: ""
        steps:
          - task: UsePythonVersion@0
          - template: azure-libtiledb-darwin.yml

      - job: build2_python
        dependsOn: [build1_libtiledb, build1_libtiledb_on_linux]
        condition: always()
        variables:
          cibw_test_requires: "pytest"
          USE_CIBW_VERSION: 2.17.0
        strategy:
          matrix:
            linux_py:
              imageName: "ubuntu-latest"
              CIBW_SKIP: "cp36-* cp37-* *_i686 pp* *musllinux*"
              CIBW_BUILD_VERBOSITY: 3
              CIBW_ARCHS_MACOS: ""
            macOS_py:
              imageName: "macOS-12"
              MACOSX_DEPLOYMENT_TARGET: 11
              TILEDB_INSTALL: "$(Pipeline.Workspace)/.libtiledb_dist/$(LIBTILEDB_SHA)-macos-x86_64"
              CIBW_ARCHS_MACOS: "x86_64"
              CIBW_SKIP: "cp36-* cp37-* pp*"
              CIBW_TEST_SKIP: "cp37-*"
              CIBW_BUILD_VERBOSITY: 3
            macOS_arm64_py:
              imageName: "macOS-12"
              MACOSX_DEPLOYMENT_TARGET: 11
              TILEDB_INSTALL: "$(Pipeline.Workspace)/.libtiledb_dist/$(LIBTILEDB_SHA)-macos-arm64"
              CIBW_BUILD_VERBOSITY: 3
              CIBW_ARCHS_MACOS: "arm64"
              # NumPy is only available in CPython 3.8+ on macOS-arm64
              CIBW_SKIP: "cp36-* cp37-* pp*"
            windows_py:
              imageName: "windows-latest"
              CIBW_SKIP: "cp36-* cp37-* *-win32 pp*"
              CIBW_BUILD_VERBOSITY: 3
              CIBW_ARCHS_MACOS: ""
        pool:
          vmImage: $(imageName)

        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.10"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

          - script: git tag -f $(TILEDBPY_VERSION)

          - task: DownloadPipelineArtifact@2
            displayName: "Download libtiledb artifact"
            inputs:
              artifactName: 'libtiledb-$(Agent.OS)$(CIBW_ARCHS_MACOS)'
              path: $(TILEDB_INSTALL)

          # we have to archive the files because azp breaks newlines in a bare directory restore
          - bash: |
              set -x
              if [[ "$AGENT_OS" == "Windows_NT" ]]; then
                7z x -o${TILEDB_INSTALL}/ ${TILEDB_INSTALL}/libtiledb-${LIBTILEDB_VERSION}-${LIBTILEDB_SHA} -y
              else
                tar xzf ${TILEDB_INSTALL}/libtiledb-${LIBTILEDB_VERSION}-${LIBTILEDB_SHA} -C ${TILEDB_INSTALL};
                find ${TILEDB_INSTALL}
              fi

              # Copy libz (temporary work-around for delocate on macOS)
              if [[ "$AGENT_OS" == "Darwin" ]]; then
                cp ${TILEDB_INSTALL}/lib/libz.1.dylib $BUILD_REPOSITORY_LOCALPATH
                install_name_tool -change libz.1.dylib ${BUILD_REPOSITORY_LOCALPATH}/libz.1.dylib ${TILEDB_INSTALL}/lib/libtiledb.dylib
              fi
            displayName: "Extract libtiledb files"

          - bash: |
              # Set the CIBW_ENVIRONMENT from bash in order to get forward slashes because somewhere in  the
              # cmd/cibw/python chain we end up losing the slashes entirely if we use a job-level variable.
              MPATH=$(python -c 'import os; print(os.environ["TILEDB_INSTALL"].replace("\\","/"))')
              export CIBW_ENVIRONMENT="TILEDB_PATH=${MPATH}"
              # !!! DO NOT PUT OTHER VARIABLES IN THIS SECTION - vars w/out expansions go below !!!"
              echo "##vso[task.setvariable variable=CIBW_ENVIRONMENT]$CIBW_ENVIRONMENT"
            displayName: "Set CIBW_ENVIRONMENT"
            condition: and(succeeded(), ne(variables['Agent.OS'], 'Linux'))

          - bash: |
              set -xe pipefail

              mv ${TILEDB_INSTALL} .libtiledb
              export TILEDB_INSTALL=.libtiledb
              export CIBW_ENVIRONMENT="TILEDB_PATH=${TILEDB_INSTALL} TILEDB_WHEEL_BUILD=1"
              # use the requirements_wheel.txt with numpy pins to ensure ABI compatibility
              export CIBW_TEST_COMMAND="python -c 'import tiledb'"
              # copy libtiledb into usr/local for auditwheel to find
              export CIBW_BEFORE_BUILD="cp -R .libtiledb/* /usr/local"
              ls -lR "${TILEDB_INSTALL}"

              python -c "import os; print(os.environ.get('CIBW_ENVIRONMENT', None))"
              git rev-parse HEAD
              python3 -m pip install --upgrade -r requirements_dev.txt
              python3 -m build . --sdist --outdir wheelhouse
              pip3 install cibuildwheel==${USE_CIBW_VERSION}
              cibuildwheel --output-dir wheelhouse .
            displayName: "Build and test wheels (Linux)"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

          - bash: |
              set -xe pipefail

              export TILEDB_WHEEL_BUILD=1
              export SYSTEM_VERSION_COMPAT=0 # https://github.com/numba/numba-benchmark/issues/14#issuecomment-1167675905
              # use the requirements_wheel.txt with numpy pins to ensure ABI compatibility
              if [[ "$CIBW_ARCHS" != "arm64" ]]; then
                export CIBW_TEST_COMMAND="python -c 'import tiledb'"
              fi
              echo "${TILEDB_INSTALL}"

              python -c "import os; print(os.environ.get('CIBW_ENVIRONMENT', None))"
              git rev-parse HEAD
              python3 -m pip install --upgrade -r requirements_dev.txt
              python3 -m build . --sdist --outdir wheelhouse
              pip3 install cibuildwheel==${USE_CIBW_VERSION}
              cibuildwheel --output-dir wheelhouse .
            displayName: "Build and test wheels (macOS)"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

          - script: |
              echo ON
              set "TILEDB_WHEEL_BUILD=1"
              :: # Have not managed to get this working AZP quoting breaks the command
              :: set CIBW_TEST_COMMAND=python -c \"import tiledb\""
              echo "cibw env: "
              echo "%CIBW_ENVIRONMENT%"
              echo "tiledb_install: "
              echo "%TILEDB_INSTALL%"
              python -c "import os; print(os.environ['CIBW_ENVIRONMENT'])"
              python -c "import platform; print('py compiler: ', platform.python_compiler())"
              :: this runs under cmd on windows, which we need to use vcvarsall
              call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
              git rev-parse HEAD
              python -m pip install --upgrade -r requirements_dev.txt
              python3 -m build . --sdist --outdir wheelhouse
              pip install cibuildwheel==%USE_CIBW_VERSION%
              cibuildwheel --output-dir wheelhouse .
              :: delete the sdist because we *do not* want files with CRLF endings
              :: (if windows builds finish last then the windows sdist will be
              ::  overwrite any others in the artifact publishing step)
              del /q wheelhouse\*.tar.gz
            displayName: "Build and test wheels (Windows)"
            condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

          - template: azure-print-logs.yml

          - task: PublishBuildArtifacts@1
            inputs: { pathtoPublish: "wheelhouse" }

          - bash: |
              set -x
              echo "TILEDB_SRC -----------------------------------------"
              find $TILEDB_SRC || true
              echo "TILEDB_BUILD -----------------------------------------"
              find $TILEDB_BUILD || true
              echo "TILEDB_INSTALL -----------------------------------------"
              find $TILEDB_INSTALL || true
            displayName: "List all the files"
            condition: always()

      - job: trigger_fail_build
        dependsOn: [build2_python]
        condition: and(failed(), startsWith(variables['Build.SourceBranchName'], 'azure-wheel-test-'))
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              connectionType: "connectedServiceName"
              connectedServiceName: "TileDB-Py-Test"
              method: "POST"
              body: |
                {
                "event_type": "failed",
                "client_payload": {"build_id:": "$(Build.BuildId)"}
                }
              urlSuffix: "repos/$(Build.Repository.Name)/dispatches"
              waitForCompletion: "false"

      - job: trigger_success_build
        dependsOn: [build2_python]
        condition: and(succeeded(), startsWith(variables['Build.SourceBranchName'], 'azure-wheel-test-'))
        pool: server
        steps:
          - task: InvokeRESTAPI@1
            condition: succeeded()
            inputs:
              connectionType: "connectedServiceName"
              connectedServiceName: "TileDB-Py-Test"
              method: "POST"
              body: |
                {
                "event_type": "succeeded",
                "client_payload": {"build_id:": "$(Build.BuildId)"}
                }
              urlSuffix: "repos/$(Build.Repository.Name)/dispatches"
              waitForCompletion: "false"
