# Don't build any extra formats
formats: []

# Use RTD config version 2
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# Set build OS to avoid build failures with old compiler
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
